apiVersion: v1
kind: ConfigMap
metadata:
  name: wiki-composer-settings
  labels:
    {{- include "sag-wiki.labels" . | nindent 4 }}
data:
  composer.local.json: |
    {
      "extra": {
        "merge-plugin": {
          "include": [
            "extensions/*/composer.json",
            "skins/*/composer.json"
          ]
        }
      }
    }
