apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-common-pvc
spec:
  storageClassName: "nfs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "wiki-common-pv"